### ISSUE TITLE
Sounds and Music Level 1 - 8

### ISSUE THREAD

**Issue by xcezz** [PSMGGamesSS2015/PSMG_SS_2015_Antichamber#29]
We need ideas and references for the occuring sounds and background music for level 1 - 8.
@FelixKalley & @xcezz

**Comment by FelixKalley** [comment]
Sounds definitely needed for now:
- Walk
- Run
- Jump/Land
- Pick Up
- Put Down
- Cubes falling
- Door open
- Door closed
- Trying to open a Locked Door
- Trigger Sound
- Special Gliding Doors
- Knock on Door
- Acquire Weapon

Additional sounds needed maybe:
- Falling in Pit
- Special Indication Sound for Image Tipps
- Special Indication Sound for Text Tipps
- Sound for Completing Levels
- Sound for "Teleport" to Levelstart
- Knock on Wall
- Knock on Glass

Music References: 
Pendulum - Coma (https://www.youtube.com/watch?v=Ejzlg0SeKnY)
Q.U.B.E Soundtrack (https://www.youtube.com/watch?v=LiLMd8-DeJY&list=PL1251316A95F4D811)
All Music from AlphaEcho (more or less impossible to finde online, i have it on HDD)

Rückfrage bei Martin zwecks Musik selber machen:
![screenshot 2015-06-03 11 26 30](https://cloud.githubusercontent.com/assets/7516526/7957109/40e131cc-09e5-11e5-8ee2-b48d5830faad.png)
