### ISSUE TITLE
Sketching of level 9 and onwards

### ISSUE THREAD

**Issue by xcezz** [PSMGGamesSS2015/PSMG_SS_2015_Antichamber#39]
In order to model these levels, we first need to create a hand-drawn sketch for each level.

**Comment by FelixKalley** [comment]
scheinbar gibts hier in Kommentaren keinen pdf support, daher nur per link https://www.dropbox.com/s/jxit5ed1m29krgl/Level%20Skizzen%20Felix.pdf?dl=0
